export {default as HomeScreen} from './homeScreen'
export {default as RestaurantInfo} from './restaurantInfo'
export {default as Object} from './lottieObject'
export {default as PotatoImage} from './potatoImage'
export {default as NewLocation} from './newLocation'
export {default as AvocadoImage} from './avocadoImage'