export {default as HomeScreen} from './homeScreen'
export {default as RestaurantInfo} from './restaurantInfo'
export {default as Object} from './lottieObject'
export {default as PickedImage} from './pickedImage'
export {default as NewLocation} from './newLocation'
